onLoadMission = "Custom Warlords w/Vanilla content! Find us @ www.discord.io/warlords";
onLoadName = "Warlords unOFFICIAL";
loadScreen = "images\loadScreen.paa";
overviewPicture = "A3\Data_F_Warlords\data\wl_logo_ca.paa";
overviewText = $STR_A3_WL_modRules;
dev = "Josef Zemanek";
author = "BIS + GamerDad";
respawn = "BASE";
respawnDelay = 30;

corpseManagerMode = 1;
corpseLimit = 50;
corpseRemovalMinTime = 300;
corpseRemovalMaxTime = 600;
wreckManagerMode = 1;
wreckLimit = 10;
wreckRemovalMinTime = 30;
wreckRemovalMaxTime = 60;
minPlayerDistance = 50;

WLAIRequisitonBlacklist[] = {"B_crew_F", "B_Helipilot_F", "B_Pilot_F", "O_crew_F", "O_Helipilot_F", "O_Pilot_F", "B_T_crew_F", "B_T_Helipilot_F", "B_T_Pilot_F", "O_T_crew_F", "O_T_Helipilot_F", "O_T_Pilot_F"};